CREATE TABLE IF NOT EXISTS book (
    id SERIAL PRIMARY KEY,
    isbn VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    date_added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
